2020-07-03 15:20:40,418 ERROR ----|vvv|----
2020-07-03 15:20:40,419 ERROR Running the command: msub caused an error...
2020-07-03 15:20:40,421 ERROR Traceback (most recent call last):
  File "/home/mohamed/fireworks/lib/python3.6/site-packages/fireworks/user_objects/queue_adapters/common_adapter.py", line 212, in submit_to_queue
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'msub': 'msub'

2020-07-03 15:20:40,421 ERROR ----|^^^|----
2021-06-18 09:56:21,962 ERROR ----|vvv|----
2021-06-18 09:56:21,962 ERROR Running the command: msub caused an error...
2021-06-18 09:56:21,963 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/fireworks/user_objects/queue_adapters/common_adapter.py", line 212, in submit_to_queue
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'msub': 'msub'

2021-06-18 09:56:21,963 ERROR ----|^^^|----
2021-06-18 10:03:08,683 ERROR ----|vvv|----
2021-06-18 10:03:08,683 ERROR Running the command: msub caused an error...
2021-06-18 10:03:08,684 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/fireworks/user_objects/queue_adapters/common_adapter.py", line 212, in submit_to_queue
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'msub': 'msub'

2021-06-18 10:03:08,684 ERROR ----|^^^|----
2021-06-18 10:05:01,633 ERROR ----|vvv|----
2021-06-18 10:05:01,634 ERROR Running the command: msub caused an error...
2021-06-18 10:05:01,634 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/fireworks/user_objects/queue_adapters/common_adapter.py", line 212, in submit_to_queue
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'msub': 'msub'

2021-06-18 10:05:01,634 ERROR ----|^^^|----
2021-06-18 10:06:42,913 ERROR ----|vvv|----
2021-06-18 10:06:42,913 ERROR Running the command: msub caused an error...
2021-06-18 10:06:42,914 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/fireworks/user_objects/queue_adapters/common_adapter.py", line 212, in submit_to_queue
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'msub': 'msub'

2021-06-18 10:06:42,914 ERROR ----|^^^|----
2021-06-18 11:38:26,335 ERROR ----|vvv|----
2021-06-18 11:38:26,336 ERROR Running the command: msub caused an error...
2021-06-18 11:38:26,343 ERROR Traceback (most recent call last):
  File "/home/mohamed/fireworks/lib/python3.6/site-packages/fireworks/user_objects/queue_adapters/common_adapter.py", line 212, in submit_to_queue
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'msub': 'msub'

2021-06-18 11:38:26,344 ERROR ----|^^^|----
2021-06-18 11:40:11,341 ERROR ----|vvv|----
2021-06-18 11:40:11,341 ERROR Running the command: msub caused an error...
2021-06-18 11:40:11,343 ERROR Traceback (most recent call last):
  File "/home/mohamed/fireworks/lib/python3.6/site-packages/fireworks/user_objects/queue_adapters/common_adapter.py", line 212, in submit_to_queue
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'msub': 'msub'

2021-06-18 11:40:11,343 ERROR ----|^^^|----
2021-06-18 13:03:42,458 ERROR ----|vvv|----
2021-06-18 13:03:42,459 ERROR Running the command: msub caused an error...
2021-06-18 13:03:42,460 ERROR Traceback (most recent call last):
  File "/home/mohamed/fireworks/lib/python3.6/site-packages/fireworks/user_objects/queue_adapters/common_adapter.py", line 212, in submit_to_queue
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'msub': 'msub'

2021-06-18 13:03:42,460 ERROR ----|^^^|----
2021-06-18 13:04:00,989 ERROR ----|vvv|----
2021-06-18 13:04:00,989 ERROR Running the command: msub caused an error...
2021-06-18 13:04:00,990 ERROR Traceback (most recent call last):
  File "/home/mohamed/fireworks/lib/python3.6/site-packages/fireworks/user_objects/queue_adapters/common_adapter.py", line 212, in submit_to_queue
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'msub': 'msub'

2021-06-18 13:04:00,990 ERROR ----|^^^|----
2021-06-18 13:04:18,877 ERROR ----|vvv|----
2021-06-18 13:04:18,877 ERROR Running the command: msub caused an error...
2021-06-18 13:04:18,878 ERROR Traceback (most recent call last):
  File "/home/mohamed/fireworks/lib/python3.6/site-packages/fireworks/user_objects/queue_adapters/common_adapter.py", line 212, in submit_to_queue
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'msub': 'msub'

2021-06-18 13:04:18,878 ERROR ----|^^^|----
2021-06-19 14:19:20,916 ERROR ----|vvv|----
2021-06-19 14:19:20,916 ERROR Running the command: msub caused an error...
2021-06-19 14:19:20,917 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/fireworks/user_objects/queue_adapters/common_adapter.py", line 212, in submit_to_queue
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'msub': 'msub'

2021-06-19 14:19:20,917 ERROR ----|^^^|----
2021-06-19 14:20:57,731 ERROR ----|vvv|----
2021-06-19 14:20:57,732 ERROR Running the command: msub caused an error...
2021-06-19 14:20:57,732 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/fireworks/user_objects/queue_adapters/common_adapter.py", line 212, in submit_to_queue
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'msub': 'msub'

2021-06-19 14:20:57,732 ERROR ----|^^^|----
