2021-06-18 10:05:19,227 ERROR ----|vvv|----
2021-06-18 10:05:19,227 ERROR Running the command: sbatch caused an error...
2021-06-18 10:05:19,228 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/fireworks/user_objects/queue_adapters/common_adapter.py", line 212, in submit_to_queue
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sbatch': 'sbatch'

2021-06-18 10:05:19,228 ERROR ----|^^^|----
